import Link from 'next/link'
import { onlineNikahCountries } from '../lib/online-nikah-countries'

export function getOnlineNikahFaqs(country) {
  const name = country ? onlineNikahCountries[country].name : 'Pakistan and Overseas'
  return [
    [`How do I start an online nikah enquiry from ${name}?`, 'Share the location and nationality of both partners, current marital status, preferred date and intended use of the marriage records. Begin with a consultation before sending sensitive documents or booking a ceremony.'],
    ['Can the whole process be completed without travel?', 'Initial discussions and document coordination can begin remotely. Whether travel, representation, signing or in-person steps are required depends on the proposed arrangement and authorities involved; confirm your case before booking.'],
    ['What documents should we prepare?', 'Prepare identity and relevant marital status records for review. Ask for the case-specific checklist, including any witness information, authority documents, photographs, translations or supporting evidence needed.'],
    ['Will an online nikah be accepted for immigration?', 'Acceptance must be assessed for the specific application and form of marriage. Obtain current guidance from the receiving authority or a qualified adviser before relying on a remote arrangement.'],
    ['How much do online nikah services cost?', 'Request an itemised quote covering the agreed coordination and document work. Confirm any separate registration, certificate, translation, attestation or delivery costs.'],
    ['Can you help with a marriage certificate afterwards?', 'Discuss the record you need, where registration is coordinated and whether certificate assistance is included in the service or arranged separately.'],
  ]
}

export function OnlineNikahHero({ country }) {
  const info = country ? onlineNikahCountries[country] : null
  return <div className="karachi-hero-description"><h2>{info ? `Online Nikah Support for Couples in ${info.region}` : 'Online Nikah Services for Pakistan & Overseas Pakistanis'}</h2><p className="hero-text">{info ? info.intro : 'Bring your online nikah plans into one clear conversation. GenZ Marriage supports enquiries from Pakistan, the UAE, UK, USA, Canada, Saudi Arabia, Australia, Oman and Qatar. Discuss document preparation, participation and registration questions before choosing an appointment, whether your partner is nearby or in another country.'}</p><h3>Nikah Coordination, Documentation &amp; Clear Fees</h3><p className="hero-text">Explain where both partners are located and how you intend to use your marriage records. Review the proposed participation and signing arrangements, agreed Haq Mehr and applicable witness requirements. Request a clear quote and discuss any <Link href="/marriage-certificate">marriage certificate assistance</Link> you need. Remote coordination can begin with an enquiry; the steps and document acceptance should be confirmed for your circumstances.</p></div>
}

export function OnlineNikahDetails({ country }) {
  const info = country ? onlineNikahCountries[country] : null
  const location = info ? info.region : 'Pakistan & Overseas'
  const requirements = [
    ['Identity, age & eligibility', 'Prepare current passports, CNICs or NICOPs as applicable, and identify the nationality and location of both partners. Age and eligibility need review for the jurisdictions involved. Resolve differences in personal details before paperwork is prepared.'],
    ['Voluntary consent & participation', 'Both partners must freely agree to the marriage. Discuss how participation, identity confirmation and signing will be handled in the proposed arrangement. Do not assume that a video call alone settles every requirement.'],
    ['Witnesses & agreed marriage terms', 'Review applicable witness requirements with the person conducting the nikah and confirm identification and participation arrangements. Agree Haq Mehr and the marriage terms to be recorded before the document is finalised.'],
    ['Previous marriage records', 'Disclose any previous or existing marriage. Provide relevant divorce or deceased spouse’s death records for review. Questions about marital status or legal eligibility should be resolved before scheduling.'],
    ['Representation & supporting paperwork', 'If representation is proposed, obtain individual advice on the required authority and how it should be executed. Confirm whether translations, photographs, affidavits or other records are needed for your case.'],
    ['Receiving authority’s checklist', 'Identify where the marriage records will be used. Confirm the accepted form of marriage and the requested documents for that specific application before booking certificate, translation or attestation work.'],
  ]
  const steps = [
    ['Start your consultation', 'Share both partners’ locations, nationality and marital status. Explain your preferred date, the service you need and any official application or deadline connected to the marriage records.'],
    ['Review the proposed arrangement', 'Discuss participation, consent, witnesses and any representation. Establish which matters require professional advice or confirmation from a receiving authority before you proceed.'],
    ['Prepare and review documents', 'Complete the confirmed checklist and review personal details and agreed terms for the Nikah Nama. Resolve missing information and document inconsistencies before the appointment.'],
    ['Confirm scope, fees & scheduling', 'Agree the included services and separate charges. Coordinate a time suitable for participants and confirm how the nikah and signing arrangements will be managed.'],
    ['Proceed with the agreed nikah formalities', 'Complete the approved participation and signing arrangements with the relevant person conducting the nikah. Retain the details of the agreed document and registration follow up.'],
    ['Registration & document follow up', 'Confirm who will coordinate the applicable Pakistan registration steps and how updates will be provided. Agree certificate requests, document delivery and any further work separately where needed.'],
  ]
  return <section className="karachi-details section-pad" aria-labelledby="online-details-title">
    <div className="section-intro"><p className="eyebrow">Online nikah, carefully coordinated</p><h2 id="online-details-title">Online Nikah in {location}: Requirements, Procedure &amp; Documents</h2><p className="intro-text">Plan the ceremony and documentation together, with a clear understanding of the arrangements to confirm.</p></div>
    <nav className="guide-links" aria-label="Online nikah country pages">{Object.entries(onlineNikahCountries).map(([slug, item]) => <Link key={slug} href={`/online-nikah/${slug}`} aria-current={country === slug ? 'page' : undefined}>Online Nikah in {item.name}<span aria-hidden="true">↗</span></Link>)}</nav>
    <div className="karachi-detail-grid city-local-details"><article><h3>{info ? `Planning Your Online Nikah from ${info.name}` : 'Choose the Country Connected to Your Enquiry'}</h3><p>{info ? info.focus : 'Choose Pakistan or the overseas country where you are based to start a focused enquiry. If your plans involve more than one country, explain the connection between them. Your location, the proposed marriage arrangements and the place where documents will be submitted all matter to the discussion.'}</p><p>Tell us whether you are arranging a new marriage or asking about records for an existing marriage. Keep legal eligibility, ceremony coordination and document acceptance on your checklist as distinct questions.</p></article><article><h3>What Can Be Coordinated Remotely?</h3><p>Begin your enquiry and discuss the document checklist online. Explain whether either partner can attend in Pakistan and whether you need to explore remote participation or representation. Signing, official submissions and acceptance abroad require confirmation for the specific arrangement.</p><p>Before booking, establish which tasks are included, who handles each stage and whether any in-person attendance is needed. Plan from that confirmed scope rather than a general promise of completion without travel.</p></article></div>
    <section className="karachi-requirements"><h2>Online Nikah Requirements for Couples in {location}</h2><p>Use these preparation points to discuss your case. The final checklist depends on the proposed form and place of marriage, identity records and intended use of documents.</p><dl className="requirements-list">{requirements.map(([title, text]) => <div key={title}><dt>{title}</dt><dd>{text}</dd></div>)}</dl></section>
    <section className="karachi-procedure"><h2>Online Nikah Procedure: From Enquiry to Records</h2><p>Review the arrangements before choosing a date. A ceremony appointment, registration and certificate delivery may have separate timelines.</p><ol className="procedure-list">{steps.map(([title, text]) => <li key={title}><h3>{title}</h3><p>{text}</p></li>)}</ol></section>
    <div className="karachi-detail-grid">
      <article><h3>Online Nikah Fees &amp; Service Scope</h3><p>Request an itemised quote for your actual requirements. Confirm whether the proposed service includes document review, nikah coordination and registration follow up. Certificate assistance, translation, attestation and delivery should be identified separately where applicable.</p><p>Ask how payments are acknowledged and what happens if preparation is incomplete or an appointment needs rescheduling. A clear written scope helps both partners understand the arrangements before making a commitment.</p></article>
      <article><h3>Scheduling Across Countries &amp; Time Zones</h3><p>Share a preferred time with the time zone stated clearly. Include the availability of both partners and any participants who need to join. Confirm technical and participation arrangements before the appointment, with a contact method for last-minute coordination.</p><p>Keep time for document review before the ceremony. If you have a travel or application deadline, disclose it early and ask which stages depend on authority processing rather than appointment availability.</p></article>
      <article><h3>Nikah Nama &amp; Marriage Certificate Assistance</h3><p>Review the names, identity details, Haq Mehr and agreed terms recorded in the Nikah Nama before signing. Confirm the copies you will receive and the follow-up arrangements for registration. Where Pakistan registration applies, Section 5 of the Muslim Family Laws Ordinance, 1961 addresses Muslim marriage registration.</p><p>For a separate certificate enquiry, share the exact document request. Visit our <Link href="/marriage-certificate">marriage certificate page</Link> to discuss existing records, missing information or the next documentation step.</p><p className="legal-reference"><a href="https://pakistancode.gov.pk/pdffiles/administratordf5df7bd70945d88e28f6a85c1a9ef6b.pdf" target="_blank" rel="noopener noreferrer">Registration reference: Pakistan Code</a></p></article>
      <article><h3>Using Marriage Documents Overseas</h3><p>Acceptance of a marriage and acceptance for a particular visa, sponsorship or administrative process require separate consideration. Obtain current guidance for the actual remote or representative arrangement proposed, rather than assuming that possession of a certificate answers every question.</p><p>Ask the receiving authority which records, translations or authentications it requires. If the proposed arrangement is unsuitable for your intended application, resolve that before the ceremony rather than relying on later document work to change its acceptance.</p></article>
    </div>
    <div className="karachi-quote-strip"><div><p className="eyebrow">Start your enquiry</p><h3>{info ? `Discuss Online Nikah from ${info.name}` : 'Discuss Your Online Nikah Plans'}</h3><p>Share both partners’ locations, your preferred date and documentation needs.</p></div><a className="button button-primary" href="#contact">Request a Quote <span aria-hidden="true">↗</span></a></div>
    <div className="guide-links"><Link href="/online-nikah">All Online Nikah Services<span aria-hidden="true">↗</span></Link><Link href="/court-marriage">Court Marriage in Pakistan<span aria-hidden="true">↗</span></Link><Link href="/marriage-certificate">Marriage Certificate Assistance<span aria-hidden="true">↗</span></Link></div>
  </section>
}
